import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

import Navbar from "@/components/Navbar/Navbar";

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${geistSans.variable} ${geistMono.variable}`}>
      <body className="relative min-h-screen overflow-x-hidden">
        {/* Background Gradients for Glassmorphism */}
        <div className="fixed inset-0 z-[-1] bg-bg-main">
          {/* Top-left deep purple orb */}
          <div className="absolute top-[-10%] left-[-10%] w-[50%] h-[50%] rounded-full bg-purple-900/30 blur-[120px] mix-blend-screen pointer-events-none"></div>
          {/* Bottom-right indigo orb */}
          <div className="absolute bottom-[-10%] right-[-10%] w-[60%] h-[60%] rounded-full bg-indigo-900/20 blur-[150px] mix-blend-screen pointer-events-none"></div>
          {/* Center subtle teal orb */}
          <div className="absolute top-[40%] left-[30%] w-[40%] h-[40%] rounded-full bg-teal-900/10 blur-[100px] mix-blend-screen pointer-events-none"></div>
        </div>
        
        <Navbar />
        <main className="relative z-10">{children}</main>
      </body>
    </html>
  );
}
